[package]
name = "em_thread"
version = "0.1.0"
edition = "2021"

[dependencies]
rtt_main = {path = "../../packages/rtt_rust-latest/rtt_main/"}
rtt_rs2 = {path = "../../packages/rtt_rust-latest/rtt_rs2/"}
